In [ ]:
import numpy as np
a = np.array([10,20 ,30,40,50,60,70,80,90,100])

np.where(a>70)

(array([7, 8, 9]),)

### 练习题 1：数组创建与属性查看



**题目：** 使用 `arange()` 函数创建一个从 1 到 12 的一维等差数组，然后使用 `reshape()` 方法将其重塑为 3行4列的二维数组 。请分别打印出该数组的维度（`ndim`）、形状（`shape`）和元素总个数（`size`）。  

In [17]:
import numpy as np
a = np.arange(1, 13)
print(a)
b = a.reshape(3, 4)
print(b)
print("数组维度（ndim）：", b.ndim)    # 维度：2维
print("数组形状（shape）：", b.shape)  # 形状：(3, 4)
print("元素总个数（size）：", b.size)  # 总数：12

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
数组维度（ndim）： 2
数组形状（shape）： (3, 4)
元素总个数（size）： 12


### 练习题 2：数据类型转换



**题目：** 创建一个包含浮点数 `[1.5, 2.6, 3.7, 4.8]` 的 NumPy 数组。使用 `astype()` 方法将该数组的数据类型转换为 32位整数 (`np.int32`)，并打印转换前后的数组及其数据类型名称 (`dtype.name`) 。  


In [18]:
import numpy as np
c  = np.array([1.5, 2.6, 3.7, 4.8])

d = c.astype(np.int32)# 转换为32位整数

# 打印转换前后
print("转换前数组:", c)
print("转换前类型:", c.dtype.name)
print("转换后数组:", d)
print("转换后类型:", d.dtype.name)

转换前数组: [1.5 2.6 3.7 4.8]
转换前类型: float64
转换后数组: [1 2 3 4]
转换后类型: int32


### 练习题 3：二维数组的切片操作



**题目：** 创建一个二维数组 `arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])`。请使用切片操作获取原数组的前两行，以及第 2 到第 3 列的子数组（即期望得到 `[[2, 3], [6, 7]]`）。  

In [20]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = a[:2, 1:3]
print(result)

[[2 3]
 [6 7]]


### 练习题 4：花式索引与布尔索引

**题目：** 给定一维数组 `arr = np.array([10, 15, 20, 25, 30, 35])`。

1. 使用花式索引提取第 1、3、5 个元素（即索引为 0, 2, 4 的元素）。  

   

   

2. 使用布尔索引提取数组中所有大于 20 的元素 。  


In [35]:
import numpy as np
a = np.array([10, 15, 20, 25, 30, 35])
# 1. 花式索引
fancy = a[[0, 2, 4]]
print("花式索引结果:", fancy)
# 2. 布尔索引
bool_idx = a[(a > 20) & (a < 30)]
print("布尔索引结果:", bool_idx)

花式索引结果: [10 20 30]
布尔索引结果: [25]


### 练习题 5：数组运算与广播机制



**题目：** 创建一个形状为 `(3, 4)` 的全 0 数组（使用 `zeros()` 函数）和一个一维数组 `arr_b = np.array([1, 2, 3, 4])` 。利用 NumPy 的广播机制，将这两个数组相加并打印出结果 。  

In [ ]:
import numpy as np
a = np.zeros((3, 4))
b = np.array([1, 2, 3, 4])

sum = a + b
print(sum)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


### 练习题 6：通用函数的应用

**题目：** 给定数组 `x = np.array([1, 4, 9, 16])` 和 `y = np.array([2, 1, 4, 5])`。

1. 使用一元通用函数 `np.sqrt()` 计算数组 `x` 中每个元素的平方根 。  

   

   

2. 将得到的平方根数组与数组 `y` 结合，使用二元通用函数 `np.maximum()` 找出对应位置上的最大值 。  

In [25]:
import numpy as np
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

sqrt_x = np.sqrt(x)
print("平方根:", sqrt_x)

max_arr = np.maximum(sqrt_x, y)
print("对应位置最大值:", max_arr)

平方根: [1. 2. 3. 4.]
对应位置最大值: [2. 2. 4. 5.]


### 练习题 7：数组的转置



**题目：** 创建一个形状为 `(2, 3, 4)` 的三维数组 `arr = np.arange(24).reshape((2, 3, 4))` 。使用 `transpose()` 方法将该数组的轴顺序转换为 `(1, 0, 2)`，并打印转换后新数组的形状（`shape`） 。  

In [28]:
import numpy as np

arr = np.arange(24).reshape((2, 3, 4))
print("原数组:", arr)
print("原数组形状:", arr.shape)
new_arr = arr.transpose((1, 0, 2))
print("转置后数组:", new_arr)
print("新数组形状:", new_arr.shape)

原数组: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
原数组形状: (2, 3, 4)
转置后数组: [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
新数组形状: (3, 2, 4)


### 练习题 8：条件逻辑运算



**题目：** 给出两个一维数组 `arr_x = np.array([1, 5, 7])`，`arr_y = np.array([2, 6, 8])` 以及一个布尔条件数组 `arr_con = np.array([True, False, True])` 。请使用 `np.where()` 函数，当条件为 `True` 时取 `arr_x` 中的对应元素，当条件为 `False` 时取 `arr_y` 中的对应元素 。  

In [30]:
import numpy as np

arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

res = np.where(arr_con, arr_x, arr_y)
print(res)

[1 6 7]


### 练习题 9：统计运算与排序



**题目：** 创建二维数组 `arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])` 。  



1. 使用统计方法计算该数组所有元素的算术平均值（`mean()`）。  

   

   

2. 使用 `sort()` 方法对该数组沿着 `axis=0` 的方向（按列顺序从小到大）进行排序，并打印排序后的结果 。  

In [ ]:
import numpy as np
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])

mean_val = arr.mean()
print("平均值:", mean_val)

# 2. 按列排序 axis=0
arr_sorted = np.sort(arr, axis=0)
print("按列排序后:\n", arr_sorted)

平均值: 3.888888888888889
按列排序后:
 [[3 2 2]
 [4 3 2]
 [6 6 7]]


### 练习题 10：随机数生成与矩阵点积



**题目：** 1. 设置随机数种子为 `10`（使用 `np.random.seed()` 保证每次生成的随机数一致）。 2. 使用随机数模块生成两个形状为 `(2, 2)` 且服从 [0, 1) 均匀分布的随机矩阵 A 和 B（使用 `np.random.rand()`）。 3. 使用线性代数模块的 `dot()` 方法计算矩阵 A 和矩阵 B 的点积 。  

In [32]:
import numpy as np

np.random.seed(10)

A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

dot_res = np.dot(A, B)
print("A:\n", A)
print("B:\n", B)
print("点积结果:\n", dot_res)

A:
 [[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
B:
 [[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
点积结果:
 [[0.38861894 0.18917279]
 [0.46418833 0.71193035]]


In [38]:
3 and 2

2